# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
orbs:
  android: circleci/android@1.0.3
  codecov: codecov/codecov@1.2.0

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-test:
    # These next lines define the Android machine image executor: https://circleci.com/docs/2.0/executor-types/
    executor:
      name: android/android-machine

    steps:
      # Checkout the code as the first step.
      - checkout

      # The next step will run the unit tests
      - android/run-tests:
          test-command: ./gradlew -Pcoverage -PfirebaseDisable testFullDebugUnitTest jacocoTestFullDebugUnitTestReport

      # Then start the emulator and run the Instrumentation tests!
      #      - android/start-emulator-and-run-tests:
      #          test-command: ./gradlew connectedDebugAndroidTest
      #          system-image: system-images;android-25;google_apis;x86

      # And finally run the release build
      #      - run:
      #          name: Assemble release build
      #          command: |
      #            ./gradlew assembleRelease
      - codecov/upload:
          file: './app/build/jacoco/jacoco.xml'
      - codecov/upload:
          file: './automation/build/jacoco/jacoco.xml'
      - codecov/upload:
          file: './combo/build/jacoco/jacoco.xml'
      - codecov/upload:
          file: './core/build/jacoco/jacoco.xml'
      - codecov/upload:
          file: './dana/build/jacoco/jacoco.xml'
      - codecov/upload:
          file: './danar/build/jacoco/jacoco.xml'
      - codecov/upload:
          file: './danars/build/jacoco/jacoco.xml'
      - codecov/upload:
          file: './database/build/jacoco/jacoco.xml'
      - codecov/upload:
          file: './insight/build/jacoco/jacoco.xml'
      - codecov/upload:
          file: './medtronic/build/jacoco/jacoco.xml'
      - codecov/upload:
          file: './omnipod-common/build/jacoco/jacoco.xml'
      - codecov/upload:
          file: './omnipod-dash/build/jacoco/jacoco.xml'
      - codecov/upload:
          file: './omnipod-eros/build/jacoco/jacoco.xml'
      - codecov/upload:
          file: './rileylink/build/jacoco/jacoco.xml'
      - codecov/upload:
          file: './wear/build/jacoco/jacoco.xml'

workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  sample:
    jobs:
      - build-and-test