# libs.versions.toml
[versions]
gradlePlugin = "8.7.1"
googleServices = "4.4.2"
kotlin = "2.0.21"
wearable = "2.9.0"
room = "2.6.1"
dagger = "2.48.1"
mockito = "5.6.0"
okhttp = "4.12.0"
retrofit = "2.9.0"
kotlinx-serialization = "1.7.3"
kotlinx-coroutines = "1.9.0"

[plugins]
android-library = { id = "com.android.library" }
klint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.1.1" }
moduleDependencyGraph = { id = "com.savvasdalkitsis.module-dependency-graph", version = "0.12" }


[libraries]
com-android-tools-build = { group = "com.android.tools.build", name = "gradle", version.ref = "gradlePlugin" }
com-google-gms = { group = "com.google.gms", name = "google-services", version.ref = "googleServices" }

com-google-dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }
com-google-dagger-android = { group = "com.google.dagger", name = "dagger-android", version.ref = "dagger" }
com-google-dagger-android-processor = { group = "com.google.dagger", name = "dagger-android-processor", version.ref = "dagger" }
com-google-dagger-android-support = { group = "com.google.dagger", name = "dagger-android-support", version.ref = "dagger" }

com-google-firebase-gradle = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version = "3.0.2" }
com-google-firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version = "33.4.0" }
com-google-firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
com-google-firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
com-google-firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging-ktx" }
com-google-firebase-auth = { group = "com.google.firebase", name = "firebase-auth-ktx" }
com-google-firebase-database = { group = "com.google.firebase", name = "firebase-database-ktx" }
com-google-android-gms-playservices-measurement = { group = "com.google.android.gms", name = "play-services-measurement-api", version = "22.1.2" }
com-google-android-gms-playservices-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version = "18.2.0" }
com-google-android-gms-playservices-location = { group = "com.google.android.gms", name = "play-services-location", version = "21.3.0" }

com-google-android-material = { group = "com.google.android.material", name = "material", version = "1.12.0" }
com-google-android-flexbox = { group = "com.google.android.flexbox", name = "flexbox", version = "3.0.0" }

com-google-android-wearable = { group = "com.google.android.wearable", name = "wearable", version.ref = "wearable" }
com-google-android-wearable-support = { group = "com.google.android.support", name = "wearable", version.ref = "wearable" }

com-google-guava = { group = "com.google.guava", name = "guava", version = "32.1.3-jre" }
com-google-code-gson = { group = "com.google.code.gson", name = "gson", version = "2.10.1" }
com-google-crypto-tink = { group = "com.google.crypto.tink", name = "tink-android", version = "1.10.0" }

kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-allopen = { group = "org.jetbrains.kotlin", name = "kotlin-allopen", version.ref = "kotlin" }
kotlin-serialization = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }

kotlinx-serialization-bom = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-bom", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json" }
kotlinx-serialization-protobuf = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-protobuf" }
kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core" }

kotlinx-coroutines-bom = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-bom", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android" }
kotlinx-coroutines-rx3 = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-rx3" }
kotlinx-coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava" }
kotlinx-coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test" }

kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version = "0.6.1" }

androidx-room = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-rxjava3 = { group = "androidx.room", name = "room-rxjava3", version.ref = "room" }
androidx-room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }

io-reactivex-rxjava3-rxjava = { group = "io.reactivex.rxjava3", name = "rxjava", version = "3.1.17" }
io-reactivex-rxjava3-rxkotlin = { group = "io.reactivex.rxjava3", name = "rxkotlin", version = "3.0.1" }
io-reactivex-rxjava3-rxandroid = { group = "io.reactivex.rxjava3", name = "rxandroid", version = "3.0.2" }
com-uber-rxdogtag2-rxdogtag = { group = "com.uber.rxdogtag2", name = "rxdogtag", version = "2.0.2" }

com-squareup-okhttp3-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
com-squareup-okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
com-squareup-retrofit2-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
com-squareup-retrofit2-adapter-rxjava3 = { group = "com.squareup.retrofit2", name = "adapter-rxjava3", version.ref = "retrofit" }
com-squareup-retrofit2-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }

org-mozilla-rhino = { group = "org.mozilla", name = "rhino", version = "1.7.14" }

org-mockito-android = { group = "org.mockito", name = "mockito-android", version.ref = "mockito" }
org-mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
org-mockito-junit-jupiter = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }
org-mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version = "5.1.0" }